# .streamlit/secrets.toml

testing_mode = true
payment_provider = "stripe" #bmac if using Buy Me A Coffee
stripe_api_key_test = "rk_test_51OWqYpDEvKci1tgSJ1SeaxBYHgL9qy9S7DtT4aaMl38piIA8giWnsD6OBKE7BR79ITC08UXCDnpxKOwiGFUPthtJ00K4blMEwE" #only needed if using Stripe
stripe_api_key = "sk_live_..." #only needed if using Stripe
stripe_link = "https://buy.stripe.com/..." #only needed if using Stripe
stripe_link_test = "https://buy.stripe.com/test_14k7tHbwrbIg3UAeUU" #only needed if using Stripe
client_id = "247918173944-fboi4ep232f2beaemb9g7388tav87jpv.apps.googleusercontent.com"
client_secret = "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"
redirect_url_test = 'http://localhost:8501/'
redirect_url = "http://localhost:8501/"
bmac_api_key = "ey..." #only needed if using buy me a coffee
bmac_link = "https://www.buymeacoffee.com/..." #only needed if using buy me a coffee

[connections.gsheets]

spreadsheet =  "https://docs.google.com/spreadsheets/d/1iXS_SWJn6QYSeOWxb0yfF6CkxkLBmvzWko1Rlk9ScdQ/"  
worksheet = "<worksheet-gid-or-folder-id>"  # worksheet GID is used when using Public Spreadsheet UR    L, when usign service_account it will be picked as folder_id 
type = "service_account"
project_id = "financialanalysis-408912"
private_key_id = "6477fd3c2ad8c73cf9662c4b7f6b02707427c6cd"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC9G0PI1L/jLByM\nVdUQebQKFSgn+WqX1Jg2+nO4d8b/9f8RZqgxZxa+H4BGVtS0WXF9ILOkHctHKQj1\nZdBpesRvYkn8YopdY4vw1KCO3Pm2+AEOKWOXNtDM3ymO1SoNM293XCrCSJNZ8FKV\nEHXaBv1Jw1Xfrfn40NCymQfNBuwT9xDnGrlazy1mENMITxuiNQzK3sMcjhY/Ry1f\nVSdVvrRJQZPbbYbu18QIdOzQpDSguD6SyeICozRWnslbC5S+/bVCd3uVK/zo7dRS\nhx7XjKN5cNuiKJPjP/XLANF+wQ6lkArP4FYHSWcbS7HmefwRP2VI0v5NpxZVUmKk\nTjhii8fTAgMBAAECggEADS7PZOVf6HL0x9uxRLrB5Z9f80QcktphL26k4+EwYDuX\n58X48lNgxH7nBFWdR7f3L2U44LdVqm+ejkI7aymsc/oCyl4G40fDQ6tZngai6dxp\ncRagOLRmOJdTYFT/33e3IjesoL/1IGSefSxulXUTRzHKKhOzb2MEiXly5RoXGbUV\neL/ErD+Jwbq61ZZ++S4YSyvdN8RPWJqbir85CPyOqsws1rQ09C6w6U9I0PthmECc\nJMmNMpI05v35hoi/6QRVRfg4uwG6WG++j1pFRA/rSXSWENI1Rst2hPmmI49PB1Qo\n/uGT36Bm0dEiOZW6cy80YC7PTvUOOxFbZ4pyAvBIEQKBgQDnUi7i1SqxV9M/H56X\nt1P5DvAudGBMALHXJIZfypY8xkFMiBrE8YXYpWW5sSmYFlXywPlwAqyaaXrC6W/h\nQRcA17rBdGba/JFp+FMr0DWbsgcTt79ZL/vDUDqYQochqfF2lhO0mBz0b6Xt27QG\nZFu9d+TLMRrp12eEkKbYHou4JwKBgQDRSB9r6Emif6Az/6BPCik0FoxsyBHlwwzK\n9zm0SyckNPRreV4iFZ8JFbjARqd7IKfBhkKkpcg8GIlXvTN9ma4rRDbXdVFwspqO\no1+7r5lpM2qODBc6RT/KTokVkT3tW6tpSGklm1AZCpvdN5DM3nFL4VaGnXE/kuWv\nl9PROh8ydQKBgG6nW5Jakj+fWYgaogzFP8AmKzKtrNrugiP+buEn0dJkrBvmB5gq\nSPKnvA+l9dWw6ZBkS24PeW2sA3N1o3VHY6+dgtLD0efzZcQha/fLc7l04fnGrhwF\n3hNCL6ViPa4W01D83ZRIJ6GuPtuXe3iLTW9HCQVCCjPOPNCnOYiso/2FAoGBALQa\nrW/f5/7Ads5JH1zmEa+R+CdlxoFE6q2BNVfDlVvDdtVHDYunr8XRu709EMUVxUj2\nkkO/qCKPuyKW4MkmiI0Tl160x/GEwx4d2zVaWVv/s6OrJBIxpkQkcjTtWa37RfjF\nKDgFAVmLl7c5KpQkmrwCoMQYmm1rrd7/enqE2nRBAoGBALf4FaBEUj5dg8aoLLLK\ne5jH15Zs0p/F4P+oVwno7CL/bNB/NnSVB68NWg1FNWVGd4KQXKfF4PLA1KDFkWc7\nDvRYoSj9G9zHbhoMMVpJ9p0gdV3lfkZteuud1gXXCcAuToPDy6O54pLHdsycsdGf\n6h1ycMdhTqwHO7H3wYr6z/TP\n-----END PRIVATE KEY-----\n"
client_email = "python-googshets-access@financialanalysis-408912.iam.gserviceaccount.com"
client_id = "116055154955437608197"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/python-googshets-access%40financialanalysis-408912.iam.gserviceaccount.com"

[connections.stripe]